export enum Muscle {
    Triceps = "Triceps",
    TricepsLonghead = "Triceps (Long Head)",
    Biceps = "Biceps",
    Quad = "Quad",
    Hamstring = "Hamstring",
    Calve = "Calve",
    Glute = "Glute",
    Neck = "Neck",
    DeltRear = "Delt (Rear)",
    DeltFront = "Delt (Front)",
    DeltLateral = "Delt (Lateral)",
    Brachioradialis = "Brachioradialis",
    Forearm = "Forearm",
    Lat = "Lat",
    AbsLow = "Abs (Low)",
    AbsHigh = "Abs (High)",
    AbsOblique = "Abs (Oblique)",
    AbsSerratus = "Abs (Serratus)",
    LowerBack = "Lower Back",
    Chest = "Chest",
    HipFlexor = "Hip Flexor",
    Erector = "Erector",
    TrapHigh = "Trap (High)",
    TrapLow = "Trap (Low)"
}